// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package request

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_7f73548e33e655fe) }

var fileDescriptor_7f73548e33e655fe = []byte{
	// 97 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe6, 0x62, 0x0f, 0x82, 0x08,
	0x08, 0x09, 0x70, 0x31, 0xe7, 0x16, 0xa7, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98,
	0x46, 0x1a, 0x5c, 0x1c, 0x01, 0x39, 0x89, 0x99, 0x79, 0xc1, 0x81, 0x3e, 0x42, 0x32, 0x5c, 0x2c,
	0xae, 0xc9, 0x19, 0xf9, 0x42, 0x1c, 0x7a, 0x50, 0xf5, 0x52, 0x70, 0x96, 0x12, 0x43, 0x12, 0x1b,
	0xd8, 0x34, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xc6, 0x6c, 0x5a, 0x5e, 0x00, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlainSQLClient is the client API for PlainSQL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlainSQLClient interface {
	Echo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Request, error)
}

type plainSQLClient struct {
	cc *grpc.ClientConn
}

func NewPlainSQLClient(cc *grpc.ClientConn) PlainSQLClient {
	return &plainSQLClient{cc}
}

func (c *plainSQLClient) Echo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Request, error) {
	out := new(Request)
	err := c.cc.Invoke(ctx, "/PlainSQL/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlainSQLServer is the server API for PlainSQL service.
type PlainSQLServer interface {
	Echo(context.Context, *Request) (*Request, error)
}

// UnimplementedPlainSQLServer can be embedded to have forward compatible implementations.
type UnimplementedPlainSQLServer struct {
}

func (*UnimplementedPlainSQLServer) Echo(ctx context.Context, req *Request) (*Request, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}

func RegisterPlainSQLServer(s *grpc.Server, srv PlainSQLServer) {
	s.RegisterService(&_PlainSQL_serviceDesc, srv)
}

func _PlainSQL_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlainSQLServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PlainSQL/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlainSQLServer).Echo(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlainSQL_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PlainSQL",
	HandlerType: (*PlainSQLServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _PlainSQL_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "request.proto",
}
